# Generated by Django 4.0.3 on 2022-03-24 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='區域')),
            ],
        ),
        migrations.CreateModel(
            name='Maintain_Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='類別')),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='位置')),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.PositiveIntegerField(default=1, verbose_name='樓層')),
                ('machine_id', models.CharField(max_length=10, verbose_name='機器編號')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='home.area')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='home.maintain_group')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='home.place')),
            ],
        ),
    ]
