# Generated by Django 4.0.3 on 2022-03-25 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='狀態')),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(max_length=50, verbose_name='備註')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='記錄時間')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='home.machine')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='home.status')),
            ],
        ),
    ]
