# Generated by Django 4.0.3 on 2022-03-25 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_area_name_alter_place_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='machine_id',
            field=models.CharField(max_length=10, unique=True, verbose_name='機器編號'),
        ),
    ]
