# Generated by Django 4.0.3 on 2022-03-26 15:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_machine_machine_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='user',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='user'),
            preserve_default=False,
        ),
    ]
