# Generated by Django 3.2.13 on 2022-04-14 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_record_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='record_today',
            field=models.BooleanField(default=False, verbose_name='今日更新'),
        ),
    ]
