# Generated by Django 3.2.13 on 2022-04-14 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_machine_record_today'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='record_today',
            field=models.PositiveIntegerField(default=0, verbose_name='今日更新'),
        ),
    ]
